# Site settings
title: 'Thomas Maroulis'
description: 'I am a software team lead in London'
description2: 'Also, tinkerer, sci-fi literature reader, space geek, general geek, etc.'
url: 'https://dalamar42.github.io'
baseurl: '/'
# enforce_ssl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Thomas Maroulis'
#  email: ''
#  twitter_username: ''
  github_username:  'dalamar42'
  linkedin_username:  'thomas-maroulis-77201489'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
